--- Representa os modos de layout disponíveis para posicionamento de um Control.
---
--- O layout define como o Control é posicionado e redimensionado dentro do
--- retângulo base do pai (ou da raiz quando não há pai).
--- @alias NodeUI.Control.Layout
--- | "TOP_LEFT"
--- | "TOP_RIGHT"
--- | "BOTTOM_LEFT"
--- | "BOTTOM_RIGHT"
--- | "CENTER_LEFT"
--- | "CENTER_RIGHT"
--- | "CENTER_TOP"
--- | "CENTER_BOTTOM"
--- | "CENTER"
--- | "LEFT_WIDE"
--- | "RIGHT_WIDE"
--- | "TOP_WIDE"
--- | "BOTTOM_WIDE"
--- | "VCENTER_WIDE"
--- | "HCENTER_WIDE"
--- | "HEXPAND"
--- | "VEXPAND"
--- | "EXPAND"
--- | "FULL_RECT"
--- | "CUSTOM"

--- Define como eventos de mouse são propagados entre Controls.
--- @alias NodeUI.Control.MouseFilter
--- | "STOP"   Consome o evento e impede propagação.
--- | "PASS"   Permite propagação após processar o evento.
--- | "IGNORE" Ignora o evento completamente.

--- Lista de sinais emitidos por um Control.
--- @alias NodeUI.Control.Signals
--- | "MOUSE_PRESSED"       Quando um botão do mouse é pressionado.
--- | "MOUSE_RELEASED"      Quando um botão do mouse é solto.
--- | "MOUSE_MOVED"         Quando o mouse se move sobre o Control.
--- | "WHEEL_MOVED"         Quando o scroll do mouse é usado.
--- | "MOUSE_FOCUS_CHANGED" Quando o foco de mouse entra ou sai.

--- Modo de alinhamento de algum elemento.
--- @alias NodeUI.Control.AlignmentMode
--- | "BEGIN"  Alinhado ao início.
--- | "CENTER" Alinhado ao meio.
--- | "END"    Alinhado ao fim.

--- Eixo horizontal ou vertical.
--- @alias NodeUI.Control.Axis
--- | "HORIZONTAL"
--- | "VERTICAL"

--- Representa a conexão de um sinal no **`Control`**.
--- @class NodeUI.Control.SignalConnection
--- @field method string Nome do método chamado quando o sinal é emitido.
--- @field owner table   Objeto dono do método.
