--- @class NodeUI.Control.Settings
--- @field layout_mode? NodeUI.Control.LayoutMode
--- @field mouse_focus_mode? NodeUI.Control.MouseFocusMode

--- @alias NodeUI.Control.LayoutMode
--- | "absolute"
--- | "top_left"
--- | "top_right"
--- | "bottom_left"
--- | "bottom_right"
--- | "center"
--- | "center_left"
--- | "center_right"
--- | "center_top"
--- | "center_bottom"
--- | "full_rect"
--- | "left_wide"
--- | "right_wide"
--- | "top_wide"
--- | "bottom_wide"
--- | "h_center_wide"
--- | "v_center_wide"

--- @alias NodeUI.Control.MouseFocusMode
--- | "stop" Recebe o evento e impede que outros recebam
--- | "pass" Recebe o evento e permite que filhos/outros processem
--- | "ignore" Ignora eventos de mouse
