--- Maneira com a textura será exibida horizontal ou verticalmente.
--- @alias NodeUI.StyleBoxTexture.AxisStretchMode
--- | "STRETCH"  Distorce a textura.
--- | "TILE"     Repete a textura para caber na dimensão.
--- | "TILE_FIT" Repete a textura e a distorce para caber na dimensão.
