--- Lista de sinais emitidos por um **`Button`**.
--- @alias NodeUI.Button.Signals
--- | NodeUI.BaseButton.Signals

--- Estados de um **`Button`**.
--- @alias NodeUI.Button.State
--- | "NORMAL"
--- | "PRESSED"
--- | "HOVER"
--- | "HOVER_PRESSED"
--- | "DISABLED"
